Modify three mistakes in  DP-GEN/learnDoc/DP-GEN_handson.md
deepmodeling/tutorials pull request #62
Opened 2022-12-29 12:48 UTC by Q-Query

Correct three mistakes in  DP-GEN/learnDoc/DP-GEN_handson.md

2023-01-13 01:17 UTC, njzjz approved these changes

2023-01-14 01:07 UTC, likefallwind approved these changes

2023-01-14 01:09 UTC, likefallwind requested changes
please pr to devel branch

2024-08-09 19:18 UTC, njzjz commented on source/Tutorials/DP-GEN/learnDoc/DP-GEN_handson.md
> +| "resource"| dict| The definition of resources.|
should be `resources` instead of `resource`

2025-10-04 04:29 UTC, closed without merging